apiVersion: v1
kind: Service
metadata:
  name: dogs-service
spec:
  selector:
    app: nginx-dogs
  ports: 
    - port: 80
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: cats-service
spec:
  selector:
    app: nginx-cats
  ports: 
    - port: 80
      targetPort: http