apiVersion: apps/v1
kind: Deployment
metadata:
  name: dogs-deployment
spec:
  # replicas: 2 It's reccomended to remove this number so there's no conflict with HPA
  selector:
    matchLabels:
      app: nginx-dogs
  template:
    metadata:
      labels:
        app: nginx-dogs
    spec:
      volumes:
        - name: dogs-resources
          configMap:
            name: dogsconfigmap
      containers:
        - name: nginx
          image: nginx:1.25.2
          volumeMounts:
            - name: dogs-resources
              mountPath: "/usr/share/nginx/html"
          ports:
            - name: http
              containerPort: 80